# for arch base systems 

#exec-once = /usr/lib/gnome-polkit/polkit-gnome-authentication-agent-1
#exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = /usr/lib/mate-polkit/polkit-mate-authentication-agent-1

#for fedora and debain base systems
# exec-once = /usr/libexec/polkit-mate-authentication-agent-1 &

exec-once = dunst
exec-once = waybar
exec-once = gammastep -t 5700:3600 -l -21:149
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = swaybg -i "/home/$(whoami)/wallpapers/v627-aew-41-technologybackground.jpg"  -m fill
exec-once = fcitx5 -d --replace
exec-once = nm-applet
exec-once = hyprctl dispatch workspace 6 && kitty fish -c "bash ~/tmux_setup.sh ; exec fish"
